### ISSUE TITLE
non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by caochao** [ETCDEVTeam/emerald-rs#278]
i got a error message "non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R" while using rpc interface "emerald_signTransaction" .
it happens occasionally.
i have found a similar issue [eth.accounts.signTransaction: expected r & s to be treated as quantity, not data #1170](https://github.com/ethereum/web3.js/issues/1170).
could you provide some helps?

**Comment by r8d8** [comment]
@caochao, can you provide input values for crashed rpc call?

**Comment by caochao** [comment]
@r8d8 let me have a try, it happens occasionally

**Comment by splix** [comment]
fixed #315
