### ISSUE TITLE
SignTransaction get wrong result while chainId is not 61

### ISSUE THREAD

**Issue by maoxs2** [ETCDEVTeam/emerald-rs#299]
In emerald-wallet, it shows that `Emerald Vault returned signature from wrong Sender`
the tx sent to emerald-js is right so I guess it might be emerald-rs (emerald-cli)'s fault, But I dont know how to deal with it. 
New chainId is 111. Do I need to change the calculation of sigV?

**Comment by r8d8** [comment]
@maoxs2, nope no changes to siqV required from user.
Will test and fix it.

**Comment by maoxs2** [comment]
Bug still exists.

My chainId is 111, so if do calc the v will be 257 which is more than u8::max_value(), so it will lead to an overflow. 

solved with removing all u8 chainId/sig.v and replaced with u16.

Thanks for your help.
