### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [ETCDEVTeam/emerald-rs#62]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by dulanov** [comment]
@dtolnay look at another projects, all of them use `rustc-serialize`, it is one of more mature crate ever created, authors of serde gave a recommendation stop to use `rustc-serialize` in flaivor of `serde` because `rustc-serialize` no longer supported, but for simple tasks like hex serializations it's a best choice for many years.

**Comment by dulanov** [comment]
Good guys, we use `rustc-serialize` for hex & simple json serialization stuff and i think yes, for next iteration we can migrate to `serde` completely because our another main dependency - `jsonrpc` already using it.

**Comment by dtolnay** [comment]
@dulanov hmm, was this done or is it being tracked elsewhere?

**Comment by dulanov** [comment]
@dtolnay we ported all main RPC stuff to Serde 1.0 simultaneously with used dependencies (jsonrpc and reqwest), great job and works without questions. But there are two places where you use rustc-serialize, but generally to primitive hex encoding & decoding, I decided just not to touch it.

**Comment by dtolnay** [comment]
Okay. But this crate is still using it for JSON too right? For example [here](https://github.com/ethereumproject/emerald-rs/blob/master/src/keystore/serialize/mod.rs#L69). Is that intentional?

**Comment by dulanov** [comment]
Damn, you're right, quite a large piece of JSOn logic, it should be necessary to rewrite ;(
